# Generated by Django 3.2.9 on 2022-01-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('Author', models.CharField(max_length=40)),
                ('Subject', models.CharField(max_length=40)),
            ],
        ),
    ]
